language: python

python:
  - "3.11"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y libopenmpi-dev

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - TemporalGP -f datasets/DATASET.csv